### ISSUE TITLE
Case-insensitive commands

### ISSUE THREAD

**Issue by zavan** [zavan/monetus-fia-bot#1]
A user reported his phone makes the first letter in the commands upper case, which is not supported. Check the possibility of making commands case-insensitive.
![whatsapp image 2018-05-11 at 20 44 28](https://user-images.githubusercontent.com/1722965/39951018-5b4b117a-555c-11e8-8036-9ae10fe8d41f.jpeg)

**Comment by jhonnymoreira** [comment]
Related issue on Telegraf: https://github.com/telegraf/telegraf/issues/287

**Comment by jhonnymoreira** [comment]
Tomorrow morning I'll take a look at this issue!

**Comment by zavan** [comment]
I was thinking about this and maybe a better solution would be to implement a simple [middleware](https://telegraf.js.org/#/?id=middleware) that makes all *commands* lower case. This way there's no need to change anything else.
